version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    env_file: .env
    hostname: postgres
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - bothi-network
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 10s
      retries: 3
  web:
    build:
      context: web
    #image: ghcr.io/t0ha/midas-web:latest
    image: bothi
    env_file: .env
    hostname: web
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 127.0.0.1:4000:4000
      #volumes:
      #  - ./python:/opt
    networks:
      - bothi-network

networks:
  bothi-network:
    driver: bridge
