name: Build Docker Image
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    
jobs:
  tests:
    name: Run code checks and tests
    uses: ./.github/workflows/code-checks.yml
    secrets: inherit
        
  build_docker_image:
    name: Build Image
    runs-on: ubuntu-24.04
    needs: [tests]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building and publishing an image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ghcr.io/t0ha/lama-bot:latest

  deploy_to_do:
    name: Deploy to Digital Ocean App
    runs-on: ubuntu-24.04
    needs: [build_docker_image]
    steps:
      - name: Deploy to DO Apps
        uses: inspire-labs-tms-tech/digital-ocean-deploy-action@2.0.2
        with:
          force: "false" 
          api-key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app-id: 9e8c2aae-c365-40b1-8cf5-4127790f8c96
